{
 "title": ".NET OpenTelemetry",
 "time": { "from": "2024-12-01T21:34:59.671Z", "to": "2024-12-01T21:38:05.268Z" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total[$__rate_interval])) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_memory_usage_bytes", "legendFormat": "Process" },
    {
     "expr": "process_runtime_dotnet_gc_committed_memory_size_bytes",
     "legendFormat": ".NET Committed"
    },
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total",
     "legendFormat": ".NET Allocations"
    }
   ]
  },
  {
   "title": "Garbage Collections Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(process_runtime_dotnet_gc_collections_count_total[1m])",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes",
     "legendFormat": "{{generation}}"
    }
   ]
  }
 ]
}